_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  basic_auth: 0
  block: 0
  blog_post_mailer: 0
  breakpoint: 0
  ckeditor5: 0
  dblog: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  jsonapi: 0
  jsonapi_extras: 0
  link: 0
  mailchimp: 0
  mailchimp_campaign: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  mailsystem: 0
  media: 0
  media_library: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path_alias: 0
  rest: 0
  restui: 0
  serialization: 0
  svg_image_field: 0
  swiftmailer: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  webform: 0
  webform_mailchimp: 0
  webform_rest: 0
  webform_ui: 0
  views: 10
  minimal: 1000
theme:
  stark: 0
  claro: 0
profile: minimal
